export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAILURE = "COURSE_LIST_FAILURE";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAILURE = "COURSE_DETAILS_FAILURE";

export const COURSE_SAVE_REQUEST = "COURSE_SAVE_REQUEST";
export const COURSE_SAVE_SUCCESS = "COURSE_SAVE_SUCCESS";
export const COURSE_SAVE_FAILURE = "COURSE_SAVE_FAILURE";

export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_FAILURE = "COURSE_DELETE_FAILURE";

export const COURSE_UPDATE_REQUEST = "COURSE_UPDATE_REQUEST";
export const COURSE_UPDATE_SUCCESS = "COURSE_UPDATE_SUCCESS";
export const COURSE_UPDATE_FAILURE = "COURSE_UPDATE_FAILURE";