export const STUDENT_SIGNIN_REQUEST = "STUDENT_SIGNIN_REQUEST";
export const STUDENT_SIGNIN_SUCCESS = "STUDENT_SIGNIN_SUCCESS";
export const STUDENT_SIGNIN_FAILURE = "STUDENT_SIGNIN_FAILURE";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAILURE = "STUDENT_REGISTER_FAILURE";

export const STUDENT_UPDATE_REQUEST = "STUDENT_UPDATE_REQUEST";
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAILURE = "STUDENT_UPDATE_FAILURE";

export const STUDENT_ISVERIFIED_REQUEST = "STUDENT_ISVERIFIED_REQUEST";
export const STUDENT_ISVERIFIED_SUCCESS = "STUDENT_ISVERIFIED_SUCCESS";
export const STUDENT_ISVERIFIED_FAILURE = "STUDENT_ISVERIFIED_FAILURE";

export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAILURE = "STUDENT_LIST_FAILURE";

export const STUDENT_LOGOUT = "STUDENT_LOGOUT";
