export const TEACHER_SIGNIN_REQUEST = "TEACHER_SIGNIN_REQUEST";
export const TEACHER_SIGNIN_SUCCESS = "TEACHER_SIGNIN_SUCCESS";
export const TEACHER_SIGNIN_FAILURE = "TEACHER_SIGNIN_FAILURE";

export const TEACHER_REGISTER_REQUEST = "TEACHER_REGISTER_REQUEST";
export const TEACHER_REGISTER_SUCCESS = "TEACHER_REGISTER_SUCCESS";
export const TEACHER_REGISTER_FAILURE = "TEACHER_REGISTER_FAILURE";

export const TEACHER_UPDATE_REQUEST = "TEACHER_UPDATE_REQUEST";
export const TEACHER_UPDATE_SUCCESS = "TEACHER_UPDATE_SUCCESS";
export const TEACHER_UPDATE_FAILURE = "TEACHER_UPDATE_FAILURE";

export const TEACHER_ISVERIFIED_REQUEST = "TEACHER_ISVERIFIED_REQUEST";
export const TEACHER_ISVERIFIED_SUCCESS = "TEACHER_ISVERIFIED_SUCCESS";
export const TEACHER_ISVERIFIED_FAILURE = "TEACHER_ISVERIFIED_FAILURE";

export const TEACHER_LOGOUT = "TEACHER_LOGOUT";